### PR TITLE
use multiple dispatch to polish our wrappers

### PR DESCRIPTION
**Pull request by JerryChen97**
Mostly about the {CPU, GPU} cases.

### CODE REVIEW

**Comment by Roger-luo** [comment]
just a notice: remember to pull & checkout from the master branch. so you don't have this conflict thing again.

**Comment by JerryChen97** [comment]
> just a notice: remember to pull & checkout from the master branch. so you don't have this conflict thing again.

Oh thanks for notification. I will checkout everytime in the future.

**Comment by JerryChen97** [comment]
@Roger-luo If available please help check whether or not now the multiple dispatching is proper.

**Comment by Roger-luo** [comment]
I think you can just generate the wrapper for Array and CuArray with an extra for loop

```
for MT in [CuArray, Array]
 for T in [ComplexF32, ...]
    @eval blabla
```

**Pull request merged**
